version: "3.7"

services:
  # Nginx
  nginx:
    container_name: ${APP_NAME}_nginx
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '2.0'
    volumes:
      - ./public:/var/www/public
      - ./cloudpoints:/var/www/public/cloudpoints
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs/nginx:/var/log/nginx
    ports:
      [8081:80]
